<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gck.Application\Gck.Application.csproj" />
    <ProjectReference Include="..\Gck.Persistence\Gck.Persistence.csproj" />
    <ProjectReference Include="..\Gck.Domain\Gck.Domain.csproj" />
  </ItemGroup>

</Project>
